apiVersion: 1

datasources:
  - name: prometheus-main
    uid: peaktrade-prometheus-main
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9090
    isDefault: false
    editable: false
    jsonData:
      httpMethod: GET
      prometheusType: Prometheus
