apiVersion: 1

datasources:
  - name: prometheus-local
    uid: peaktrade-prometheus-local
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9092
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
    version: 1
