apiVersion: 1

# Multi-Prometheus provisioning for PeakTrade operator workflows.
#
# These names are intentionally aligned with the canonical Grafana datasource
# variable "ds" (see dashboards): prom_*_909{2..5}
#
# Host ports:
#   prom_local_9092          -> http://host.docker.internal:9092
#   prom_shadow_9093         -> http://host.docker.internal:9093
#   prom_ai_live_9094        -> http://host.docker.internal:9094
#   prom_observability_9095  -> http://host.docker.internal:9095
#
# This file is also used by the local verification script:
#   .ops_local/scripts/obs/verify_grafana_multi_prom.sh

datasources:
  - name: prom_local_9092
    uid: prom_local_9092
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9092
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
    version: 1

  - name: prom_shadow_9093
    uid: prom_shadow_9093
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9093
    isDefault: false
    editable: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
    version: 1

  - name: prom_ai_live_9094
    uid: prom_ai_live_9094
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9094
    isDefault: false
    editable: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
    version: 1

  - name: prom_observability_9095
    uid: prom_observability_9095
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9095
    isDefault: false
    editable: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
    version: 1
